Base/urls.py
from django.contrib import admin
from django.urls import path
from Base.views import *

urlpatterns = [
    path('home/', home, name='home'),
]

carro/urls.py
from django.contrib import admin
from django.urls import path
from carro.views import *

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/",agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/",eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/",restar_producto, name="restar"),
    path("limpiar/",limpiar_carro, name="limpiar"),

    ]

proyecto_ecommerce_electronico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("", include("Categorias.urls")),
    path('about/', include('About.urls')),
    path('contacto/',include('contacto.urls')),
    path('autenticacion/',include('autenticacion.urls')),
    path('tienda/',include('tienda.urls')),
    path('carro/',include('carro.urls')),
    path('message/',include('Messages.urls')),
    path('pedidos/',include('pedidos.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

tienda/urls.py
from django.contrib import admin
from django.urls import path
from tienda.views import *

urlpatterns = [
    path('', tienda, name='tienda'),
]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models


# Create your models here.
class CategoriaProd (models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name ='categoriaProd'
        verbose_name_plural='categoriasProd'
        
 
    def __str__(self):
       return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda",null=True,blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name ='producto'
        verbose_name_plural='productos'

    def __str__(self):
        return self.nombre
    

carro/views.py
from django.shortcuts import render,redirect
from tienda.models import Producto
from carro.carro import Carro
# Create your views here.
def agregar_producto(request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect('tienda')

def eliminar_producto(request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect('tienda')

def restar_producto(request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect('tienda')

def limpiar_carro(request,producto_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect('tienda')   

tienda/views.py
from django.shortcuts import render
from tienda.models import *

# Create your views here.
def tienda(request):
    productos=Producto.objects.all()
    return render(request,'tienda/tienda.html', {"productos":productos})

tienda/templates/carro/widget.html
<table class="bg-dark table table-bordered" style="color: rgba(255, 255, 255, 0.703);">

    <thead>
        <tr>

           <th colspan="3"class="text-center">
             Carro de Compras
           </th>
           

        </tr>
        <tr>
            <th>Productos</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>

    </thead>


    <tbody>
        {% if request.session.carro.items %}
            {% for key,value in request.session.carro.items %}
               <tr class="text-center">
                  <td>{{ value.nombre}}</td>
                  <td>{{ value.cantidad}}</td>
                  <td>
                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-outline-dark mt-auto">+</a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-outline-dark mt-auto">-</a></br>
                     {{value.precio}} $
                  </td>
               </tr>
            {% endfor%}
        {%else%} 
            <tr>
               <td colspan="3">
                  <div class="alert alert-danger text-center">
                      Sin productos
                  </div>
               </td>
            </tr> 
        {% endif%} 
    </tbody>
    <tfoot>
        <tr>
           <td colspan="3">
              Total ${{ importe_total_carro}} 

           </td>
        </tr>
        {% if request.session.carro.items %}  
        <tr>
            <td colspan="3" style="text-align:center">

              <a href="#" class="btn btn-outline-dark mt-auto">HACER PEDIDO</a>
                
            </td>
        </tr>
        {% endif%}
    </tfoot>

</table>